# -*- coding: utf-8 -*-
{
    'name': 'Loan',
    'version': '15.0.1',
    'summary': 'Loan Management',
    'sequence': -1000,
    'description': """ Create module loan management""",
    'license': 'LGPL-3',
    'depends': ['base', 'crm', 'purchase', 'sale_management', 'account_accountant', 'account', 'contacts', 'aml',
                'project', 'timer', 'mail', 'helpdesk', 'website_portal_custom','account_budget'],
    'data': [
        'security/loan_security.xml',
        'data/activity.xml',
        'data/cron_notification.xml',
        'security/ir.model.access.csv',
        'wizard/partner_report.xml',
        'view/loan_request.xml',
        # 'view/loan_view.xml',
        'view/customer.xml',
        'view/calculate.xml',
        # 'view/fuel_score.xml',
        'view/liability.xml',
        'view/user_view.xml',
        'view/loan_type.xml',
        'view/sequence.xml',
        'view/orders_offers.xml',
        'view/installment.xml',
        'view/reschedule.xml',
        'view/ticket_team.xml',
        'view/activity_type.xml',
        'view/transaction.xml',
        'view/customer_crm.xml',
        'view/v_account.xml',
        'view/helpdesk_ticket.xml',
        'view/early_payment.xml',
        'view/cron_job.xml',
        'view/simah_api.xml',
        'view/flag.xml',
        'view/budget.xml',
        'view/purchase_view.xml',
        'wizard/installment_summary_wizard.xml',
        'wizard/early_payment.xml',
        'wizard/objection_note.xml',
        'report/report_action.xml',
        'report/installment_summary_template.xml',
        'report/loan_customer_template.xml',
        # 'report/contract_loan.xml',
        'report/contract_loan_full.xml',
        'report/contract_loan_murabaha.xml',
        'report/purchase_order_inherit.xml',
        'report/r_of_q_inherit.xml',
        # 'report/kyc.xml',
        # 'report/customer_report.xml',
        'report/operational_reports.xml',
        'report/request_report.xml',
        'report/partner_report_pdf.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'loan/static/src/css/partial_payment.css',
        ],
    },

    # 'assets': {
    #         'web.assets_backend': [
    #             'loan/static/src/js/loan_order.js',
    #         ],
    #     },
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
